config/routes.rb
Rails.application.routes.draw do

  resources :band_members

  root 'band_members#index'

end

app/models/band_member.rb
class BandMember < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/band_members_controller.rb
class BandMembersController < ApplicationController
  before_action :set_band_member, only: [:show, :edit, :update, :destroy]

  # GET /band_members
  # GET /band_members.json
  def index
    @band_members = BandMember.all
  end

  # GET /band_members/1
  # GET /band_members/1.json
  def show
  end

  # GET /band_members/new
  def new
    @band_member = BandMember.new
  end

  # GET /band_members/1/edit
  def edit
  end

  # POST /band_members
  # POST /band_members.json
  def create
    @band_member = BandMember.new(band_member_params)

    respond_to do |format|
      if @band_member.save
        format.html { redirect_to @band_member, notice: 'Band member was successfully created.' }
        format.json { render :show, status: :created, location: @band_member }
      else
        format.html { render :new }
        format.json { render json: @band_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /band_members/1
  # PATCH/PUT /band_members/1.json
  def update
    respond_to do |format|
      if @band_member.update(band_member_params)
        format.html { redirect_to @band_member, notice: 'Band member was successfully updated.' }
        format.json { render :show, status: :ok, location: @band_member }
      else
        format.html { render :edit }
        format.json { render json: @band_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /band_members/1
  # DELETE /band_members/1.json
  def destroy
    @band_member.destroy
    respond_to do |format|
      format.html { redirect_to band_members_url, notice: 'Band member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band_member
      @band_member = BandMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_member_params
      params.require(:band_member).permit(:name, :instrument, :bio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/band_members_helper.rb
module BandMembersHelper
end

app/views/band_members/_form.html.erb
<%= form_for(@band_member) do |f| %>
  <% if @band_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band_member.errors.count, "error") %> prohibited this band_member from being saved:</h2>

      <ul>
      <% @band_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :instrument %><br>
    <%= f.text_field :instrument %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/band_members/edit.html.erb
<h1>Editing band_member</h1>

<%= render 'form' %>

<%= link_to 'Show', @band_member %> |
<%= link_to 'Back', band_members_path %>

app/views/band_members/index.html.erb
<h1>Tech Bitch</h1>

<%= image_tag('TechBitch.jpg'); %>



<table>
  <thead>
    <tr>
      <th>Band Members</th>
      <th>Instrument</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @band_members.each do |band_member| %>
      <tr>
        <td><%= band_member.name %></td>
        <td><%= band_member.instrument %></td>
        <td><%= band_member.bio %></td>
        <td><%= link_to 'Show', band_member %></td>
        <td><%= link_to 'Edit', edit_band_member_path(band_member) %></td>
        <td><%= link_to 'Destroy', band_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band member', new_band_member_path %>

app/views/band_members/new.html.erb
<h1>New band_member</h1>

<%= render 'form' %>

<%= link_to 'Back', band_members_path %>

app/views/band_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @band_member.name %>
</p>

<p>
  <strong>Instrument:</strong>
  <%= @band_member.instrument %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @band_member.bio %>
</p>

<%= link_to 'Edit', edit_band_member_path(@band_member) %> |
<%= link_to 'Back', band_members_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TechBitch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>